### ISSUE TITLE
ROBLOSecurity changed in update and no longer works for this script.

### ISSUE THREAD

**Issue by 1grace3** [J3ldo/LimitedSniper#1]
The main script saves the cookie with `roblosec = "_"+config["cookie"].split(".ROBLOSECURITY=_")[1]` Assuming the cookie entered in configeditor contains .ROBLOSECURITY= while the cookies are now saved as something else. (Im not sure if its .RBXIDCHECK. I tried chaning it to say .ROBLOSECURITY= but it didn't work.)

**Comment by J3ldo** [comment]
Thanks for bringing this up. I will try to look into a fix as soon as possible but you may have entered the wrong cookie, but roblox can have also changed their cookie.

**Comment by J3ldo** [comment]
I tested it out and it seems like you've got the wrong cookie. I made a cookie fetcher chrome extension a few days ago and maybe you can use that: https://github.com/J3ldo/Roblox-Token-Fetcher

**Comment by J3ldo** [comment]
I think it was a problem with the token fetcher on my side. It is now resolved.
