### ISSUE TITLE
Does this snipe ugc limiteds?

### ISSUE THREAD

**Issue by DBalinga17** [J3ldo/LimitedSniper#2]
Does this snipe ugc limiteds?

**Comment by J3ldo** [comment]
Yes, just put in the id set the price to 1 and buyagain on.

**Comment by DBalinga17** [comment]
what should i put in "Amount of limiteds you want to snipe"

**Comment by DBalinga17** [comment]
is the asset id the item id?
![image](https://user-images.githubusercontent.com/113117325/230730401-10010231-5bb8-415d-8d30-5465bebbcfa3.png)

**Comment by J3ldo** [comment]
IT does not snipe UGC limiteds as it uses a different API one that does is currently in the works
